//PROFILE
export const SET_ACCOUNT = 'SET_ACCOUNT';
export const ADD_ACCOUNT = 'ADD_ACCOUNT';
export const ADD_ACCOUNT_START = 'ADD_ACCOUNT_START';
export const ADD_ACCOUNT_SUCCESS = 'ADD_ACCOUNT_SUCCESS';
export const ADD_ACCOUNT_FAIL = 'ADD_ACCOUNT_FAIL';
export const REMOVE_ACCOUNT = 'REMOVE_ACCOUNT';
export const REMOVE_ACCOUNT_START = 'REMOVE_ACCOUNT_START';
export const REMOVE_ACCOUNT_SUCCESS = 'REMOVE_ACCOUNT_SUCCESS';
export const REMOVE_ACCOUNT_FAIL = 'REMOVE_ACCOUNT_FAIL';
export const EDIT_ON = 'EDIT_ON';
export const NEW_ACCOUNT_NAME = 'NEW_ACCOUNT_NAME';
export const EDIT_ACCOUNT = 'EDIT_ACCOUNT';
export const EDIT_ACCOUNT_START = 'EDIT_ACCOUNT_START';
export const EDIT_ACCOUNT_SUCCESS = 'EDIT_ACCOUNT_SUCCESS';
export const EDIT_ACCOUNT_FAIL = 'EDIT_ACCOUNT_FAIL';
export const FETCH_ACCOUNTS_START = 'FETCH_ACCOUNTS_START';
export const FETCH_ACCOUNTS_SUCCESS = 'FETCH_ACCOUNTS_SUCCESS';
export const FETCH_ACCOUNTS_FAIL = 'FETCH_ACCOUNTS_FAIL';

//SPENDINGS
export const SET_PARAM_VALUE = 'SET_PARAM_VALUE';
export const ADD_SPENDING = 'ADD_SPENDING';
export const FETCH_SPENDINGS_START = 'FETCH_SPENDINGS_START';
export const FETCH_SPENDINGS_SUCCESS = 'FETCH_SPENDINGS_SUCCESS';
export const FECTH_SPENDINGS_FAIL = 'FECTH_SPENDINGS_FAIL';
export const UPDATE_DATA_START = 'UPDATE_DATA_START';
export const UPDATE_DATA_SUCCESS = 'UPDATE_DATA_SUCCESS';
export const UPDATE_DATA_FAIL = 'UPDATE_DATA_FAIL';
export const ADD_SPENDING_START = 'ADD_SPENDING_START';
export const ADD_SPENDING_SUCCESS = 'ADD_SPENDING_SUCCESS';
export const ADD_SPENDING_FAIL = 'ADD_SPENDING_FAIL';
export const ADDING_INIT = 'ADDING_INIT';
export const DELETE_SPENDING_START = 'DELETE_SPENDING_START';
export const DELETE_SPENDING_SUCCESS = 'DELETE_SPENDING_SUCCESS';
export const DELETE_SPENDING_FAIL = 'DELETE_SPENDING_FAIL';
export const GET_COLUMNS_START = 'GET_COLUMNS_START';
export const GET_COLUMNS_SUCCESS = 'GET_COLUMNS_SUCCESS';
export const GET_COLUMNS_FAIL = 'GET_COLUMNS_FAIL';
export const UPDATE_DATA = 'UPDATE_DATA';
//CATEGORIES
export const FETCH_CATEGORIES_START = 'FETCH_CATEGORIES_START';
export const FETCH_CATEGORIES_SUCCESS = 'FETCH_CATEGORIES_SUCCESS';
export const FETCH_CATEGORIES_FAIL = 'FETCH_CATEGORIES_FAIL';

//AUTHORIZATION
export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';