//PROFILE
export const ADD_ACOUNT = 'ADD_ACOUNT';
export const REMOVE_ACCOUNT = 'REMOVE_ACCOUNT';
export const EDIT_ACCOUNT = 'EDIT_ACCOUNT';
export const SET_ACCOUNT = 'SET_ACCOUNT';
export const EDIT_ON = 'EDIT_ON';
export const NEW_ACCOUNT_NAME = 'NEW_ACCOUNT_NAME';
export const FETCH_ACCOUNTS_START = 'FETCH_ACCOUNTS_START';
export const FETCH_ACCOUNTS_SUCCESS = 'FETCH_ACCOUNTS_SUCCESS';
export const FETCH_ACCOUNTS_FAIL = 'FETCH_ACCOUNTS_FAIL';

//SPENDINGS
export const SET_PARAM_VALUE = 'SET_PARAM_VALUE';
export const ADD_SPENDING = 'ADD_SPENDING';
export const FETCH_SPENDINGS_START = 'FETCH_SPENDINGS_START';
export const FETCH_SPENDINGS_SUCCESS = 'FETCH_SPENDINGS_SUCCESS';
export const FECTH_SPENDINGS_FAIL = 'FECTH_SPENDINGS_FAIL';
export const UPDATE_CELL_START = 'UPDATE_CELL_START';
export const UPDATE_CELL_SUCCESS = 'UPDATE_CELL_SUCCESS';
export const UPDATE_CELL_FAIL = 'UPDATE_CELL_FAIL';
export const ADD_SPENDING_START = 'ADD_SPENDING_START';
export const ADD_SPENDING_SUCCESS = 'ADD_SPENDING_SUCCESS';
export const ADD_SPENDING_FAIL = 'ADD_SPENDING_FAIL';
export const DELETE_SPENDING_START = 'DELETE_SPENDING_START';
export const DELETE_SPENDING_SUCCESS = 'DELETE_SPENDING_SUCCESS';
export const DELETE_SPENDING_FAIL = 'DELETE_SPENDING_FAIL';

//CATEGORIES
export const FETCH_CATEGORIES_START = 'FETCH_CATEGORIES_START';
export const FETCH_CATEGORIES_SUCCESS = 'FETCH_CATEGORIES_SUCCESS';
export const FETCH_CATEGORIES_FAIL = 'FETCH_CATEGORIES_FAIL';