//PROFILE

export const ADD_ACOUNT = 'ADD_ACOUNT';
export const REMOVE_ACCOUNT = 'REMOVE_ACCOUNT';
export const EDIT_ACCOUNT = 'EDIT_ACCOUNT';
export const SET_ACCOUNT = 'SET_ACCOUNT';
export const EDIT_ON = 'EDIT_ON';
export const NEW_ACCOUNT_NAME = 'NEW_ACCOUNT_NAME';

//SPENDINGS